version: '3'
services:
  benchmarkApp:
    image: benchmark:latest
    environment:
      - BENCHMARK_DB=postgres
  postgres:
    image: postgres
    env_file:
      - ../../database.env
    ports:
      - "5432:5432"